config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end
  
  get "/sign_in_candidate", to: "sessions#sign_in_candidate", as: "sign_in_candidate"
  post "/sign_in_candidate", to: "sessions#do_sign_in_candidate"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'profile/index'
  get 'profile/job'
  get 'profile/trainings'
  get 'profile/experience'
  resources :departments
  get 'reports/index'
  get 'reports/new_employees'
  post 'reports/new_employees', to: "reports#generate_new_employees"
  get 'reports/candidates'
  post 'reports/candidates', to: "reports#candidates_search"
  resources :employees
  get '/candidates/advance_search', to: "candidates#advance_search", as: "advance_search"
  resources :candidates
  get 'backoffice/index'
  get "/jobs/fulfilled", to: "jobs#fulfilled"
  get "/jobs/unfulfilled", to: "jobs#unfulfilled"
  get "/jobs/:id/selection", to: "jobs#selection_process", as: "job_selection"
  get '/jobs/:id/candidates', to: "jobs#candidates", as: "job_candidates"
  post '/jobs/:id/select/:candidate_id', to: "jobs#select_candidate", as: "job_select_candidate"
  get "/trainings/remove/:id", to: "trainings#destroy"
  resources :jobs
  get 'home/index'
  get '/apply/:id', to: 'home#apply_job', as: "apply_job"
  resources :trainings
  resources :languages
  resources :skills
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :candidate
  validates :description, presence: true
  validates :level, presence: true
  validate :date_has_to_match


  def date_has_to_match
    if from_at > to_at
      errors.add(:from_at, "La fecha desde debe ser menor que la fecha hasta")
    end 
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: %i[ show edit update destroy ]
  before_action :require_login

  # GET /trainings or /trainings.json
  def index
    @trainings = Training.all
  end

  # GET /trainings/1 or /trainings/1.json
  def show
  end

  # GET /trainings/new
  def new
    @training = Training.new
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings or /trainings.json
  def create
    @training = Training.new(training_params)
    @candidate = Candidate.find_by_user_id(current_user.id)
    @training.candidate = @candidate
    respond_to do |format|
      if @training.save
        format.html { 
          if current_user.group == "admins"
            redirect_to trainings_url, notice: "Training was successfully created." 
          else
            redirect_to profile_trainings_url, notice: "Training was successfully created." 
          end
          }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1 or /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { 
          if current_user.group == "admins"
            redirect_to trainings_url
          else
            redirect_to profile_trainings_url
          end
          }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1 or /trainings/1.json
  def destroy
    candidate = @training.candidate
    @training.destroy

    respond_to do |format|
      format.html { redirect_to candidate, notice: "Training was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def training_params
      params.require(:training).permit(:description, :level, :from_at, :to_at, :institution)
    end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.slim
= simple_form_for(@training) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs.mb-3
    = f.input :description
    = f.input :level, collection: [["Grado", "grade"], ["Post-grado", "postgrade"], ["Maestria", "masters"], ["Doctorado", "phd"], ["Tecnico", "technical"], ["Gestion", "managment"]]
    = f.input :from_at
    = f.input :to_at
    = f.input :institution

  .form-actions.mb-3
    = f.button :submit, class: "btn btn-success"

app/views/trainings/edit.html.slim
.card 
    .card-body 
        h1.card-title Editando Capacitacion
        .card-text
            == render 'form'
            = link_to t('back').titleize, trainings_path, class: "btn btn-secondary"

app/views/trainings/index.html.slim
h1 = t('listing trainings').titleize

table.table
  thead
    tr
      th = t("activerecord.models.candidate.one").titleize
      th = t('activerecord.attributes.training.description').titleize
      th = t('activerecord.attributes.training.level').titleize
      th = t('activerecord.attributes.training.from_at').titleize
      th = t('activerecord.attributes.training.to_at').titleize
      th = t('activerecord.attributes.training.institution').titleize
      th
      th
      th

  tbody
    - @trainings.each do |training|
      tr
        td = training.candidate.name
        td = training.description
        td = training.level
        td = training.from_at
        td = training.to_at
        td = training.institution
        td = link_to 'Show', training, class: "btn btn-primary"
        td = link_to 'Edit', edit_training_path(training), class: "btn btn-success"
        td = button_to 'Destroy', training, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger"

br

= link_to t('new training').titleize, new_training_path, class: "btn btn-primary"

app/views/trainings/new.html.slim
.card 
    .card-body 
        h1.card-title = t("new training").titleize
        .card-text
            == render 'form'
            = link_to t('back').titleize, trainings_path, class: "btn btn-secondary"

app/views/trainings/show.html.slim
p#notice = notice

p
  strong Description:
  = @training.description

p
  strong Level:
  = @training.level

p
  strong From at:
  = @training.from_at

p
  strong To at:
  = @training.to_at

p
  strong Institution:
  = @training.institution

=> link_to 'Edit', edit_training_path(@training)
'|
=< link_to 'Back', trainings_path