config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end
  
  get "/sign_in_candidate", to: "sessions#sign_in_candidate", as: "sign_in_candidate"
  post "/sign_in_candidate", to: "sessions#do_sign_in_candidate"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'profile/index'
  get 'profile/job'
  get 'profile/trainings'
  get 'profile/experience'
  resources :departments
  get 'reports/index'
  get 'reports/new_employees'
  post 'reports/new_employees', to: "reports#generate_new_employees"
  get 'reports/candidates'
  post 'reports/candidates', to: "reports#candidates_search"
  resources :employees
  get '/candidates/advance_search', to: "candidates#advance_search", as: "advance_search"
  resources :candidates
  get 'backoffice/index'
  get "/jobs/fulfilled", to: "jobs#fulfilled"
  get "/jobs/unfulfilled", to: "jobs#unfulfilled"
  get "/jobs/:id/selection", to: "jobs#selection_process", as: "job_selection"
  get '/jobs/:id/candidates', to: "jobs#candidates", as: "job_candidates"
  post '/jobs/:id/select/:candidate_id', to: "jobs#select_candidate", as: "job_select_candidate"
  get "/trainings/remove/:id", to: "trainings#destroy"
  resources :jobs
  get 'home/index'
  get '/apply/:id', to: 'home#apply_job', as: "apply_job"
  resources :trainings
  resources :languages
  resources :skills
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  validates :name, presence: true
  validates :department_id, presence: true
  validates :risk_level, presence: true, inclusion: {in: %w{low medium high}, message: I18n.t("%{value} is not a valid risk level")}
  validates :wage_min, presence: true, numericality: true
  validates :wage_max, presence: true, numericality: {greater_than: proc { |r| r.wage_min }, message: I18n.t("should be greater than min wage")}
  has_many :candidates, dependent: :destroy
  belongs_to :candidate, optional: true, dependent: :destroy
  belongs_to :department
  validate :cant_enable_if_no_candidate

  def select_candidate(candidate, wage, hired_date)
    employee = Employee.create(cedula: candidate.cedula, name: candidate.name, hired_date: hired_date,
      job: self, wage: wage, status: true, candidate: candidate)
    if !employee.id.nil?
      self.candidate = candidate
      self.status = false
      self.save
    end
    employee
  end

  def has_employee?
    !self.candidate.nil?
  end

  def cant_enable_if_no_candidate
    if has_employee? && self.status == true
      errors.add(:status, "no puede activar el puesto si ya tiene un candidato seleccionado")
    end 
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy candidates select_candidate selection_process ]
  before_action :require_login

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.all
  end

  def fulfilled
    @jobs = Job.where.not(candidate: nil)
    render :index
  end

  def unfulfilled
    @jobs = Job.where(candidate: nil)
    render :index
  end

  def selection_process

  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  def candidates

  end

  def select_candidate
    @candidate = Candidate.find(params[:candidate_id])
    @employee = @job.select_candidate(@candidate, params[:employee][:wage], params[:employee][:hired_date])
    if @employee.id.nil?
      render "candidates/show", status: :unprocessable_entity
    else
      redirect_to @job
    end
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:name, :risk_level, :wage_min, :wage_max, :status, :department_id)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.slim
= simple_form_for(@job) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs.mb-3
    = f.input :name
    = f.association :department
    = f.input :risk_level, collection: [[t('low'), :low], [ t('medium'), :medium], [t('high'), :high]], selected: :low
    = f.input :wage_min
    = f.input :wage_max
    = f.input :status


  .form-actions.mb-3
    = f.button :submit, class: 'btn btn-success'

app/views/jobs/candidates.html.slim
- @job.candidates.each do |candidate|

h1 = "Candidatos para el puesto #{@job.name} en #{@job.department.name}"
table.table
    thead 
        tr 
            th Candidato
            th
    tbody 
        - @job.candidates.each do |candidate|
            tr 
                td = candidate.name
                td = link_to t("show").capitalize, candidate, class: "btn btn-primary"

app/views/jobs/edit.html.slim
.card 
    .card-body 
        h1.card-title = t('editing job').titleize
        .card-text
            == render 'form'
            .btn-group
                => link_to t('show').titleize, @job, class: 'btn btn-primary'
                =< link_to t('back').titleize, jobs_path, class: 'btn btn-secondary'

app/views/jobs/index.html.slim
h1 = t('listing jobs')
= link_to t('new job').titleize, new_job_path, class: 'btn btn-primary'
ul.nav.nav-tabs
  li.nav-item = link_to "Todos", jobs_path, class: "nav-link #{(current_page?(jobs_path) ? "active" : "")}"
  li.nav-item = link_to "Contratados", jobs_fulfilled_path, class: "nav-link #{(current_page?(jobs_fulfilled_path) ? "active" : "")}"
  li.nav-item = link_to "Disponibles", jobs_unfulfilled_path, class: "nav-link #{(current_page?(jobs_unfulfilled_path) ? "active" : "")}"
table.table
  thead
    tr
      th = t("name").capitalize
      th = t("activerecord.attributes.job.risk_level").capitalize
      th = t("activerecord.attributes.job.wage_min").capitalize
      th = t("activerecord.attributes.job.wage_max").capitalize
      th = t("status").capitalize
      th
      th

  tbody
    - @jobs.each do |job|
      tr
        td = job.name
        td = t(job.risk_level)
        td = job.wage_min
        td = job.wage_max
        td = job.status ? "✅" : "❌"
        td
          .btn-group 
            a.btn.btn-primary href=job_selection_path(job) Proceso de Selección
            a.btn.btn-secondary href=job_candidates_path(job) Ver Candidatos
            = link_to t('show').capitalize, job, class: "btn btn-primary"
            = link_to t('edit').capitalize, edit_job_path(job), class: "btn btn-success"
        td
          = button_to t('destroy').capitalize, job, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger"

app/views/jobs/new.html.slim
.card 
    .card-body 
        h1.card-title = t("new job").titleize
        .card-text
            == render 'form'
            = link_to t('back').titleize, jobs_path, class: "btn btn-secondary"

app/views/jobs/selection_process.html.slim
.row
    .col
        .card 
            .card-body 
                h5.card-title Candidato Seleccionado 
                .card-text.mb-2
                    - if @job.candidate.nil?
                        p ninguno
                    - else 
                        = link_to @job.candidate.name, @job.candidate
                a.btn.btn-danger href="#" Deseleccionar
    .col
        .card 
            .card-body 
                h5.card-title Candidatos 
                table.table
                    thead 
                        tr 
                            th Candidato
                            th
                            th
                    tbody 
                        - @job.candidates.each do |candidate|
                            tr 
                                td = candidate.name
                                td = link_to t("show").capitalize, candidate, class: "btn btn-primary"

app/views/jobs/show.html.slim
p#notice = notice
.card
  .card-body 
    h5.card-title = "#{t('job').titleize}: #{@job.name}"
    .card-text
      p
        strong = t("name").capitalize
        | :
        = @job.name

      p 
        strong Departamento
        | :
        = link_to @job.department.name, @job.department

      p
        strong = t("activerecord.attributes.job.risk_level").capitalize
        | :
        = @job.risk_level

      p
        strong = t("activerecord.attributes.job.wage_min").capitalize
        | :
        = @job.wage_min

      p
        strong = t("activerecord.attributes.job.wage_max").capitalize
        | :
        = @job.wage_max

      p
        strong = t("status").capitalize
        | :
        = @job.status ? "Activo" : "Inactivo"
      - if !@job.candidate.nil?
        p 
          strong Empleado: 
          = link_to @job.candidate.employee.name, @job.candidate.employee

      .btn-group role="group"
        => link_to t('edit').titleize, edit_job_path(@job), class: "btn btn-primary"
        =< link_to t('back').titleize, jobs_path, class: "btn btn-secondary"