config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end
  
  get "/sign_in_candidate", to: "sessions#sign_in_candidate", as: "sign_in_candidate"
  post "/sign_in_candidate", to: "sessions#do_sign_in_candidate"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'profile/index'
  get 'profile/job'
  get 'profile/trainings'
  get 'profile/experience'
  resources :departments
  get 'reports/index'
  get 'reports/new_employees'
  post 'reports/new_employees', to: "reports#generate_new_employees"
  get 'reports/candidates'
  post 'reports/candidates', to: "reports#candidates_search"
  resources :employees
  get '/candidates/advance_search', to: "candidates#advance_search", as: "advance_search"
  resources :candidates
  get 'backoffice/index'
  get "/jobs/fulfilled", to: "jobs#fulfilled"
  get "/jobs/unfulfilled", to: "jobs#unfulfilled"
  get "/jobs/:id/selection", to: "jobs#selection_process", as: "job_selection"
  get '/jobs/:id/candidates', to: "jobs#candidates", as: "job_candidates"
  post '/jobs/:id/select/:candidate_id', to: "jobs#select_candidate", as: "job_select_candidate"
  get "/trainings/remove/:id", to: "trainings#destroy"
  resources :jobs
  get 'home/index'
  get '/apply/:id', to: 'home#apply_job', as: "apply_job"
  resources :trainings
  resources :languages
  resources :skills
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/language.rb
class Language < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  def self.active
    Language.where(status: true)
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: %i[ show edit update destroy ]
  before_action :require_login

  # GET /languages or /languages.json
  def index
    @languages = Language.all
  end

  # GET /languages/1 or /languages/1.json
  def show
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages or /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to language_url(@language), notice: "Language was successfully created." }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1 or /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to language_url(@language), notice: "Language was successfully updated." }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1 or /languages/1.json
  def destroy
    @language.destroy

    respond_to do |format|
      format.html { redirect_to languages_url, notice: "Language was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def language_params
      params.require(:language).permit(:name, :status)
    end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.slim
= simple_form_for(@language) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs.mb-3
    = f.input :name
    = f.input :status

  .form-actions.mb-3
    = f.button :submit, class: 'btn btn-success'

app/views/languages/edit.html.slim
.card
    .card-body
        h1.card-title = t("editing language").titleize
        .card-text
            == render 'form'
            .btn-group
                => link_to t('show').titleize, @language, class: 'btn btn-primary'
                =< link_to t('back').titleize, languages_path, class: 'btn btn-secondary'

app/views/languages/index.html.slim
h1 = t('listing languages').titleize

table.table
  thead
    tr
      th = t('id').titleize
      th = t('name').titleize
      th = t('status').titleize
      th
      th
      th

  tbody
    - @languages.each do |language|
      tr
        td = language.id
        td = language.name
        td = language.status ? "✅" : "❌"
        td = link_to t('show').capitalize, language, class: "btn btn-primary"
        td = link_to t('edit').capitalize, edit_language_path(language), class: "btn btn-primary"
        td = button_to t('destroy').capitalize, language, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger"

br

= link_to t('new language').titleize, new_language_path, class: "btn btn-primary"

app/views/languages/new.html.slim
.card 
    .card-body
        h1.card-title = t('New language')
        .card-text
            == render 'form'

            = link_to t('back').capitalize, languages_path, class: "btn btn-secondary"

app/views/languages/show.html.slim
p#notice = notice
.card 
  .card-body
    h5.card-title = "#{t('code').titleize}: #{@language.id}"
    .card-text
      p
        strong = "#{t('name').titleize}:"
        = @language.name

      p
        strong = "#{t('status').titleize}:"
        = @language.status ? "Activo" : "Inactivo"

      .btn-group role="group"
        => link_to t('edit').titleize, edit_language_path(@language), class: "btn btn-primary"
        =< link_to t('back').titleize, languages_path, class: "btn btn-secondary"