config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end
  
  get "/sign_in_candidate", to: "sessions#sign_in_candidate", as: "sign_in_candidate"
  post "/sign_in_candidate", to: "sessions#do_sign_in_candidate"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'profile/index'
  get 'profile/job'
  get 'profile/trainings'
  get 'profile/experience'
  resources :departments
  get 'reports/index'
  get 'reports/new_employees'
  post 'reports/new_employees', to: "reports#generate_new_employees"
  get 'reports/candidates'
  post 'reports/candidates', to: "reports#candidates_search"
  resources :employees
  get '/candidates/advance_search', to: "candidates#advance_search", as: "advance_search"
  resources :candidates
  get 'backoffice/index'
  get "/jobs/fulfilled", to: "jobs#fulfilled"
  get "/jobs/unfulfilled", to: "jobs#unfulfilled"
  get "/jobs/:id/selection", to: "jobs#selection_process", as: "job_selection"
  get '/jobs/:id/candidates', to: "jobs#candidates", as: "job_candidates"
  post '/jobs/:id/select/:candidate_id', to: "jobs#select_candidate", as: "job_select_candidate"
  get "/trainings/remove/:id", to: "trainings#destroy"
  resources :jobs
  get 'home/index'
  get '/apply/:id', to: 'home#apply_job', as: "apply_job"
  resources :trainings
  resources :languages
  resources :skills
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  include SearchCop
  belongs_to :job
  belongs_to :user
  has_one :employee, dependent: :destroy
  has_many :trainings, dependent: :destroy
  has_one :department, :through => :job
  has_and_belongs_to_many :languages
  has_and_belongs_to_many :skills
  accepts_nested_attributes_for :trainings, reject_if: proc { |attributes| 
    attributes["description"].blank? || attributes["institution"].blank?
  }

  search_scope :search do
    attributes :name, :cedula
    attributes job: "job.name"
    attributes puesto: "job.name"
    attributes nombre: "name"
    attributes cedula: "cedula"
    attributes salario: "desired_wage"
    attributes skill: ["skills.description"]
    attributes departamento: ["department.name"]
    attributes competencia: ["skills.description"]
    attributes idioma: ["languages.name"]
  end

  validates :name, presence: true
  validates :cedula, presence: true, uniqueness: true
  validates :desired_wage, presence: true, numericality: {greater_than: 0}
  validates_associated :trainings
  validate :cedula_valida
  before_validation :create_user
  after_destroy :clean_job

  def has_language?(lang)
    language_ids.all?(lang.id)
  end

  def create_user
    if self.id.nil? && self.user.nil?
      u = User.create(email: "#{self.cedula}@#{self.cedula}.com", password: self.cedula, group: "candidates")
      self.user = u
    end
  end

  def clean_job
    Job.where(candidate_id: self.id).each do |x|
      x.candidate_id = nil
      x.save
    end
  end

  def cedula_valida
    vnTotal = 0
    vcCedula = self.cedula.gsub("-","")
    pLongCed = vcCedula.strip.length
    digitoMult = [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1]
    if (pLongCed < 11 || pLongCed > 11)   
      errors.add(:cedula, "No es valida")
      return
    end
    for vDig in 1..pLongCed do
      vCalculo = vcCedula[vDig-1,1].to_i * digitoMult[vDig-1]
      if (vCalculo < 10)
        vnTotal += vCalculo
      else
        vnTotal += vCalculo.to_s()[0,1].to_i + vCalculo.to_s()[1,1].to_i
      end
    end
    if not (vnTotal % 10 == 0)
      errors.add(:cedula, "No es valida")
    end
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: %i[ show edit update destroy ]
  before_action :require_login
  skip_before_action :require_login, only: [:new, :create]


  # GET /candidates or /candidates.json
  def index
    @candidates = Candidate.order(created_at: :desc).search(params["buscar"])
    @buscar = params[:buscar]
  end

  def advance_search
    @buscar = params[:buscar]
    @candidates = Candidate.search(params["buscar"])
    @skills = params[:skills]
    @languages = params[:languages]
    @trainings = params[:trainings]
    @job = params[:job]
    unless params[:languages].nil?
      @candidates = @candidates.joins(:languages).where("languages.id": params[:languages])
    end
    unless params[:skills].nil?
      @candidates = @candidates.joins(:skills).where("skills.id": params[:skills])
    end
    unless @trainings.nil?
      @candidates = @candidates.joins(:trainings).where("trainings.level": params[:trainings])
    end
    unless @job.nil? || @job == "0"
      @candidates = @candidates.where(job_id: @job)
    end
    @candidates = @candidates.uniq
  end

  # GET /candidates/1 or /candidates/1.json
  def show
    if (@candidate.employee.nil?)
      @employee = Employee.new
    else
      @employee = @candidate.employee
    end
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates or /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)
    binding.pry
    respond_to do |format|
      if @candidate.save
        @candidate.trainings.each {|x| x.validate }
        if (!signed_in?)
          sign_in(@candidate.user)
        end
        format.html { 
          if current_user.group == "admins"
            redirect_to candidate_url(@candidate) 
          else
            redirect_to profile_index_url 
          end
        }
        format.json { render :show, status: :created, location: @candidate }
      else
        @candidate.trainings.each {|x| x.validate }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1 or /candidates/1.json
  def update
    respond_to do |format|
      @candidate.trainings.each {|x| x.validate }
      if @candidate.update(candidate_params)
        format.html { 
          if current_user.group == "admins"
          redirect_to candidate_url(@candidate), notice: "Candidado actualizado" 
          else
          redirect_to profile_index_path, notice: "Candidado actualizado"
          end
        }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1 or /candidates/1.json
  def destroy
    @candidate.destroy

    respond_to do |format|
      format.html { redirect_to candidates_url, notice: "Candidate was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def candidate_params
      params.require(:candidate).permit(:cedula, :name, :job_id, :desired_wage, :recommended_by, 
        experience: [:company, :job, :to, :from, :wage], 
        trainings_attributes: [:id, :description, :level, :institution, :from_at, :to_at],
        skill_ids: [],
        language_ids: [])
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.slim
= simple_form_for(@candidate) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :cedula
    = f.input :name
    = f.association :job
    = f.input :desired_wage
    = f.input :recommended_by
    = f.association :languages, as: :check_boxes, legend_tag: "label"
    = f.association :skills, as: :check_boxes, label_method: :description, collection: Skill.active.order(:description)

  h3 = t("trainings").capitalize
  - (@candidate.trainings + [Training.new]).each do |t|
    .mb-3
      - t.errors.each do |error|
        .alert.alert-danger = error.type
      .input-group.mb-3 
        input.form-control type="hidden" name="candidate[trainings_attributes][][id]" value=t.id
        span.input-group-text = t('activerecord.attributes.training.description').capitalize
        input.form-control type="text" name="candidate[trainings_attributes][][description]" value=t.description
        span.input-group-text = t('activerecord.attributes.training.level').capitalize
        select.form-select.form-control name="candidate[trainings_attributes][][level]"
          option selected=("selected" if t.level == "grade") grado 
          option selected=("selected" if t.level == "postgrade") post-grado
          option selected=("selected" if t.level == "masters") maestria 
          option selected=("selected" if t.level == "phd") doctorado 
          option selected=("selected" if t.level == "technical") tecnico 
          option selected=("selected" if t.level == "managment") gestion
      .input-group.mb-3 
        span.input-group-text = t('activerecord.attributes.training.institution').capitalize
        input.form-control type="text" name="candidate[trainings_attributes][][institution]" value=t.institution
        span.input-group-text = t('activerecord.attributes.training.from_at').capitalize
        input.form-control type="date" name="candidate[trainings_attributes][][from_at]" value=t.from_at
        span.input-group-text = t('activerecord.attributes.training.to_at').capitalize
        input.form-control type="date" name="candidate[trainings_attributes][][to_at]" value=t.to_at
        - if (t.id.nil?)
          a.btn.btn-danger.destroy_training_btn = t("destroy").capitalize
        - else
          = link_to "Eliminar", "/trainings/remove/#{t.id}", method: :delete, class: "btn btn-danger"
  a.btn.btn-primary.mb-3 id="new_training_btn" Nueva Capacatiacion

  h3 = t('experience').capitalize
  - (1..3).each do
    .input-group.mb-3
      input.form-control type="text" placeholder="Empresa" name="candidate[experience][][company]"
      input.form-control type="text" placeholder="Puesto Ocupado" name="candidate[experience][][job]"
      span.input-group-text Desde
      input.form-control type="date" placeholder="Desde" name="candidate[experience][][from]"
      span.input-group-text Hasta
      input.form-control type="date" placeholder="Hasta" name="candidate[experience][][to]"
      input.form-control type="text" placeholder="Salario" name="candidate[experience][][wage]"

  .form-actions.mb-3
    = f.button :submit, class: 'btn btn-success'

app/views/candidates/advance_search.html.slim
h1 = t("listing candidates").titleize
form.row.mb-2
  .col-12.mb-2
    input.form-control placeholder="Buscar" name="buscar"  value=@buscar
  .col-6.mb-2
    h5 Idiomas
    - Language.all.each do |l|
      .form-check 
        input.form-check-input type="checkbox" value=l.id name="languages[]" checked=(@languages&.include?(l.id.to_s) ? true : nil)
        label = l.name
  .col-6.mb-2
    h5 Competencias
    - Skill.all.each do |s|
      .form-check 
        input.form-check-input type="checkbox" value=s.id name="skills[]" checked=(@skills&.include?(s.id.to_s) ? true : nil)
        label = s.description
  .col-6.mb-2.row
    h5 Capacitaciones 
    .col-6
      .form-check 
        input.form-check-input type="checkbox" name="trainings[]" value="grade" checked=(@trainings&.include?("grade") ? true : nil)
        label Grado
      .form-check 
        input.form-check-input type="checkbox" name="trainings[]" value="postgrade" checked=(@trainings&.include?("postgrade") ? true : nil)
        label Post-grado
      .form-check 
        input.form-check-input type="checkbox" name="trainings[]" value="masters" checked=(@trainings&.include?("masters") ? true : nil)
        label Maestria
    .col-6
      .form-check 
        input.form-check-input type="checkbox" name="trainings[]" value="phd" checked=(@trainings&.include?("phd") ? true : nil)
        label Doctorado
      .form-check 
        input.form-check-input type="checkbox" name="trainings[]" value="technical" checked=(@trainings&.include?("technical") ? true : nil)
        label Técnico
      .form-check 
        input.form-check-input type="checkbox" name="trainings[]" value="managment" checked=(@trainings&.include?("managment") ? true : nil)
        label Gestión
  .col-6.mb-2 
    label.form-label Puesto
    select.form-select.form-control name="job"
      option value="0" selected=("selected" if @job == "0") Todos
      - Job.all.each do |j|
          option value=j.id selected=("selected" if @job == j.id.to_s) = j.name 
  .col-12
    button.btn.btn-secondary type="submit" Buscar
table.table
  thead
    tr
      th Cedula
      th = t("activerecord.attributes.candidate.name").capitalize
      th = t("activerecord.attributes.candidate.job").capitalize
      th = t("activerecord.attributes.candidate.desired_wage").capitalize
      th Departamento
      th = t("activerecord.attributes.candidate.recommended_by").capitalize
      th
      th

  tbody
    - @candidates.each do |candidate|
      tr
        td = candidate.cedula
        td = candidate.name
        td = link_to candidate.job.name, candidate.job
        td = candidate.desired_wage
        td = candidate.job.department.name
        td = candidate.recommended_by
        td 
          .btn-group
            = link_to t('show').capitalize, candidate, class: "btn btn-primary"
            = link_to t('edit').capitalize, edit_candidate_path(candidate), class: "btn btn-success"
        td
          = button_to t('destroy').capitalize, candidate, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger"
br

= link_to t('new candidate').titleize, new_candidate_path, class: "btn btn-primary"

app/views/candidates/edit.html.slim
.card 
    .card-body 
        h1.card-title = t('editing candidate').titleize
        .card-text
            == render 'form'

app/views/candidates/index.html.slim
h1 = t("listing candidates").titleize
form.row.mb-2
  .col-9
    input.form-control placeholder="Buscar" name="buscar"  value=@buscar
  .col-1
    button.btn.btn-secondary type="submit" Buscar
  .col-2
    a.btn.btn-primary href=advance_search_path Busqueda Avanzada
table.table
  thead
    tr
      th Cedula
      th = t("activerecord.attributes.candidate.name").capitalize
      th = t("activerecord.attributes.candidate.job").capitalize
      th = t("activerecord.attributes.candidate.desired_wage").capitalize
      th Departamento
      th = t("activerecord.attributes.candidate.recommended_by").capitalize
      th
      th

  tbody
    - @candidates.each do |candidate|
      tr
        td = candidate.cedula
        td = candidate.name
        td = link_to candidate.job.name, candidate.job
        td = candidate.desired_wage
        td = candidate.job.department.name
        td = candidate.recommended_by
        td 
          .btn-group
            = link_to t('show').capitalize, candidate, class: "btn btn-primary"
            = link_to t('edit').capitalize, edit_candidate_path(candidate), class: "btn btn-success"
        td
          = button_to t('destroy').capitalize, candidate, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger"
br

= link_to t('new candidate').titleize, new_candidate_path, class: "btn btn-primary"

app/views/candidates/new.html.slim
.card 
    .card-body 
        h1.card-title = t("new candidate").titleize
        .card-text
            == render 'form'
            = link_to t('back').titleize, candidates_path, class: "btn btn-secondary"

app/views/candidates/show.html.slim
p#notice = notice
.card
  .card-body 
    h5.card-title = "#{t('activerecord.models.candidate.one').titleize}: #{@candidate.name}"
    .card-text
      p
        strong Cedula:
        = @candidate.cedula

      p
        strong = t("activerecord.attributes.candidate.name").capitalize
        | :
        = @candidate.name

      p
        strong = t("activerecord.attributes.candidate.job").capitalize
        | :
        = link_to @candidate.job.name, @candidate.job
      p
        strong Departamento 
        | :
        = link_to @candidate.job.department.name, @candidate.job.department

      p
        strong = t("activerecord.attributes.candidate.desired_wage").capitalize
        | :
        = @candidate.desired_wage

      p
        strong = t("activerecord.attributes.candidate.recommended_by").capitalize
        | :
        = @candidate.recommended_by.nil? ? @candidate.recommended_by : "N/A"
      p
        strong Idiomas
      ul
        - @candidate.languages.each do |l|
          li = l.name
      p 
        strong Competencias
      ul
        - @candidate.skills.each do |s|
          li = s.description
      strong Capacitaciones
      - if @candidate.trainings.size > 0
        table.table
          thead
            tr
              th Descripcion
              th Nivel
              th Instituacion
              th Desde
              th Hasta
          tbody
            - @candidate.trainings.each do |t|
              tr
                td = t.description
                td = t(t.level)
                td = t.institution
                td = t.from_at
                td = t.to_at
      - else 
        p N/A
      strong Experiencia
      - if @candidate.experience.any? {|x| !x["company"].empty?}
        table.table
          thead
            tr
              th Empresa
              th Puesto
              th Desde
              th Hasta
              th Salario
          tbody
            - @candidate.experience&.each do |e|
              tr
                td = e["company"]
                td = e["job"]
                td = e["from"]
                td = e["to"]
                td = e["wage"]
      - else
        p N/A  
      - if !@candidate.employee.nil?
        p 
          strong Contratado en puesto:
          = link_to @candidate.employee.job.name, @candidate.employee.job
      - if not @candidate.job.has_employee?
        = simple_form_for(@employee, url: job_select_candidate_path(id: @candidate.job.id, candidate_id: @candidate.id)) do |f|
          = f.error_notification
          = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
          .form-inputs.mb-3
            = f.input :wage
            = f.input :hired_date, as: :date, html5: true
          .form-actions.mb-3
            = f.button :submit, "Seleccionar Candidato", class: 'btn btn-success'
      .btn-group role="group"
        => link_to t('edit').titleize, edit_candidate_path(@candidate), class: "btn btn-primary"
        =< link_to t('back').titleize, candidates_path, class: "btn btn-secondary"